:wrench: added docker files + server scripts
fiit-tp7-2023/data-processor pull request #14
Opened 2024-03-02 14:18 UTC by steboee

2024-03-02 14:34 UTC, brano-hozza requested changes

2024-03-02 14:34 UTC, brano-hozza commented on Dockerfile
> +FROM python:3.8-slim
Shouldnt this be like 3.10+?

2024-03-10 14:53 UTC, kikz0rsk commented on Dockerfile
> +FROM python:3.12
Can't we use python:3.12-alpine to make it more efficient?

2024-03-10 21:45 UTC, brano-hozza approved these changes

2024-03-10 21:45 UTC, merged